import re

from fastapi import Header, HTTPException

_SESSION_RE = re.compile(r"^[A-Za-z0-9-]{16,64}$")


def get_session_id(
    x_session_id: str | None = Header(
        default=None,
        alias="X-Session-ID",
        description="Anonymous per-browser identifier (UUID generated by the frontend).",
    ),
) -> str:
    if not x_session_id or not _SESSION_RE.fullmatch(x_session_id):
        raise HTTPException(
            status_code=400,
            detail="Missing or invalid X-Session-ID header.",
        )
    return x_session_id
