"""create analyses table

Revision ID: a589fed5da34
Revises: 
Create Date: 2026-10-05 11:17:02.164698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a589fed5da34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('log_input', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('affected_component', sa.String(length=255), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommended_fix', sa.JSON(), nullable=False),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.Column('prevention', sa.JSON(), nullable=False),
    sa.Column('devops_insight', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_analyses_severity'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_analyses_confidence'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_session_created', 'analyses', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyses_session_created', table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
